### ISSUE TITLE
코드리뷰 요청

### ISSUE THREAD

**Issue by devjjin** [devjjin/redux-todolist-assignment#1]
### 이전과제에서 추가한 기능
*  **uuidv4, shortid, nanoid**
  지난 과제때 고유한 id를 지정시 date()객체를 사용했었는데 이번에는 uuidv4를 이용했습니다. 
고유 식별성을 가지는 장점이 있지만 상세페이지에서 긴 id가 출력되는 부분과 url주소가 길어지다 보니 다른 방법을 고민하다가 nanoid,shortid라는 라이브러리를 사용해 길이를 설정할 수 있다 알게 되었습니다.
지금은 uuidv4를 적용한 상태입니다.  이럴때는 프로젝트의 요구사항에 따라 달리 적용하는게 맞는지 궁금합니다.

- ~~useRef로 inputbox focus** **(4/24리뷰 완료)
사용자가 input박스에 데이터를 입력 후, submit되면 다시 첫번째 input으로 포커싱 되도록 useRef를 사용.
입력 후 다시 인풋 박스를 선택해야 하는 번거로움을 줄이고, 사용자가 어떤 데이터 값을 입력해야하지는 명확하게 전달해줄 수 있겠다 생각했습니다.~~

* onsubmit 이벤트를 적용하면  사용자가 입력 도중이나 데이터를 잘못입력했을 때 enter를 치게 된다면 원치 않은 데이터가 저장된다는 단점도 있는 것 같습니다. 
**-> (4/24 리뷰 후 반영) confirm창을 띄워 사용자가 입력한 값이 맞는지 한번 더 체크하도록 추가**

* **버튼 style-component 조건부 렌더링**
이전에 취소,완료버튼을 같은 스타일로 적용하고 isDone값에 따라 텍스트만 다르게 출력되도록 작성했는데
취소, 완료버튼이 같은 초록색이다보니 헷갈려서 다른 색을 적용을 해보다 고민한 내용입니다.
-styled-component 코드를 작성할때  completeButton, cancelButton으로 각각의 스타일을 적용하는 코드를 작성했다가 
 생각해보니 둘은 조건부렌더링을 사용해 색을 바꿀수 있을 것 같아 하나의 버튼 스타일에서 조건부렌더링을 사용했는데, 

    - (1안) **완료/취소 버튼 component 스타일 을 따로 나눠서** 적용하는게 옳을지
    - (2안) 조건부 렌더링으로 props의 isDone 값에 따라 **조건부렌더링**으로 처리할지 
좋은 방안이 궁금합니다.

5. notFound 페이지 추가

### 질의사항
*  **삭제시 working 과 done component의 불필요한 리렌더링을 막기위한 컴포넌트 분리**
    - 1안) **기존 TodoList.jsx파일을 삭제 후 컴포넌트를 workingTodoList.jsx DoneTodoList.jsx 파일 두개로 분리**
             1) 문제점: styled-component 코드가 똑같이 중복되어 TodoListStyle.jsx 라는 파일을 추가해 로직과 스타일 부분을 분리했는데요. 
            -2) createGlobalStyle은 전역에서 관리하는데 이 TodoListStyle을 export할때 globalStyle 컴포넌트처럼 import {TodoListStyle} 이렇게 적용하고 싶었는데 방안을 찾지 못했습니다.
               3) 각각 export를 하다보니 import시에 {title,Container,ListContainer}라고 각각 불러오게 된 문제입니다.

     - **2안) TodoList.jsx파일은 유지한채, List 파일 내에서 const WorkingTodo~, const doneTodo이렇게  따로 파일로 분리하지 않고 컴포넌트를 list에 작성하고 스타일은 기존 대로 list내에서 작성**

어떤 방안이 옳을까요. 컴포넌트를 확실하게 구분하고 싶어서 현재는 1안을 적용한 상태입니다.

*  **비즈니스 로직과 스타일 로직을 분리**하고 싶은데
 예)TodoLIst 폴더에 TodoList 컴포넌트 하나랑 TodoListStyle 파일 이런식으로 구조를 가져가야 하나요?
현재는 강의 내에서 배운대로 모든 컴포넌트 내에서 style파일을 적용한 상태입니다.

*  **props와 redux**
list에서 자식 컴포넌트인 todo item에게 값을 props로 넘겨줄지 전역으로 처리해야 할지 고민했습니다.
처음엔 프로젝트 규모도 작으니 props로 넘겨주는게 직관적이고 수정하기 쉬울 것이라 생각했습니다. 
하지만 컴포넌트 간의 의존성을 낮추고 재사용성을 고려한다면 redux를 선택하는 것이 조금 더 적합하다고 생각해 redux로 작업을 했습니다.
**->(4/24 리뷰 후 반영) 답변주신대로 todolist에서 자식컴포넌트로 속성을 전달시 props로 넘겨주는 방식으로 변경했습니다. **

### 아쉬운점
- 배운 개념을 이해해보고 사용하려 했으나 useContext 부분과 생애주기에 대한 개념이 덜 숙지된 것 같습니다.
- 리뷰주신 내용들 많은 도움되고 있어 감사합니다! 너무 길고 두서없이 적은 것 같지만 답변 주시면 감사하겠습니다.
- 전체적인 코드 리뷰도 부탁드립니다!

**Comment by WooMinGy** [comment]
1. 저번 주 게더 순회 때 말씀 드린 것과 같이 규모가 커지거나 리스트가 많아진다면 따로 분리해서 리렌더링 되는 것 까지 고려하면 좋고, 그게 아니라면 굳이 분리 할 필요가 없겠죠! 코드 짜는 스타일에 따라서 달라질 수도 있구요! 제가 이 Todo 리스트를 만든다고 하면 굳이 분리하진 않겠지만(규모가 크지 않고 만약 진짜 쓰게되는 Todo 리스트를 만든다면 매일매일 다른 리스트를 보여주거나 완료한 것은 다른 page에서 볼 수 있게 하는게 더 좋을 것 같아서) 원래의 제 코드 스타일대로 간다면 각각 분리 시켜서 구성할 것 같습니다. 

2. 스타일을 적용시키는 방법은 여러가지가 있죠.(구글링) 말씀 드렸다시피 저는 현재 react native를 다루고 있어 react 웹에서의 style 적용 방법을 많이 접해 보지는 않았으나 보통 페이지별로 또는 페이지에 들어가는 컴포넌트(가장 작은 atom 단위의 컴포넌트가 아님) 별로 style 파일을 생성하여 적용하는 방법도 이전에 봤던 것 같구요. 두 번째로는 어짜피 공통적으로 쓰이는 컴포넌트들(atom 단위)의 기본적인 css 를 styled component 나  inline 스타일로 적용 시키고, 세세한 css(ex. padding, margin, justifyContent 등)을 기본 값을 정해준 뒤 props 로 옵셔널 하게 정할 수 있도록 구성하고, 컴포넌트를 사용하는 부분에서도 inline style(props 넘겨줘야 하기 때문)로 적용 시키는 방법이 있습니다. 이외에도 여러가지 방법이 있지만 회사마다 style을 관리하는 방법이 다 다르기 때문에 그 전까지는 수진님께서 스스로 기준을 세우고(예를들면 스스로 봤을 때 가장 가독성이 좋은 것 같다) style을 적용시키면 좋을 것 같습니다.

3. 저번에 말씀드린 것과 같이 todo list 에서 map을 사용했을 경우 item에 props로 전달하는 편이 더 좋아 보입니다. 여기저기서 쓰이는 데이터들이 아니며 확실하게 부모 -> 자식의 flow가 보이는 곳에서는 원치않는 순간에서의 데이터 변경(실수로 인한)을 막기 위함 입니다. 앞으로 계속 코드를 짜다보면 어떤 데이터를 전역 관리할지에 대해 점차 감이 잡혀 가실 거에요!

전체적인 코드 리뷰는 다음 레벨 과제에서 해드리겠습니다! 고생하셨어요!
